version: '3.5'

services: 
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - db_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "unisenha"
    networks: 
      - db_postgre_network

networks:
  db_postgre_network:
    driver: bridge
           
volumes:
  db_postgres_data: